Adds scroll animations to main page
p2r3/epochtal pull request #49
Opened 2024-07-24 19:50 UTC by ArcherTheReal

## PC
https://github.com/user-attachments/assets/c6e730ed-35b9-4fb8-b802-e42f3df71314

## Mobile
https://github.com/user-attachments/assets/0335c5e6-000f-42d8-82d3-14dd6cb686ad

2024-07-24 20:01 UTC, PancakeTAS requested changes

2024-07-24 20:01 UTC, PancakeTAS commented on pages/tools.js
> +}
newline pls

2024-07-24 20:06 UTC, PancakeTAS approved these changes

2024-07-25 01:18 UTC, soni801 commented
Im sorry the S annoyed me

2024-07-25 11:33 UTC, merged